### ISSUE TITLE
Скрипт для 1809 не запускается

### ISSUE THREAD

**Issue by skipik** [farag2/Setup-Windows-10-1809#1]
Получаю вот такую ругань:

![111](https://user-images.githubusercontent.com/24621645/54626349-0b760a80-4a82-11e9-8022-8a267332575d.png)

Версия последняя из master.

**Comment by farag2** [comment]
Приветствую. Спасибо, что оставил отзыв.
Во-первых, я так понял, запускается через cmd? Так что-то с кодировкой явно. Во-вторых, запускай напрямую через PowerShell или PowerShell. Или надо искать ошибку в батнике.
Ты, вроде, на ru-board есть. Можешь там продублировать вопрос в теме "Быстрая настройка Windows (рабочее место)"? Я совершенно случайно увидел, что ты создал тему тут. :)
